
  train_path: "data/train.csv"
  val_path: "data/val.csv"
  debug: false

model:
  seq_len: 12
  max_vocab_size: 15000
  embed_dim: 256
  hidden_dim: 512
  num_layers: 2
  dropout: 0.3

training:
  batch_size: 64
  lr: 0.001
  num_epochs: 25
  max_gen_tokens: 10
  early_stopping_patience: 4